[tool.commitizen]
version = "0.4.0"
bump_message = "build(version): :bookmark: update version from $current_version to $new_version"
version_schema = "semver"
version_provider = "commitizen"
version_files = ["_metadata.yml"]
update_changelog_on_bump = true
# Don't regenerate the changelog on every update
changelog_incremental = true
